const categoriesData = [
    {
        id:1,
        image:require("../../assets/images/pizza-icon.png"),
        title:'Pizza',
        selected:true
    },
    {
        id:2,
        image:require("../../assets/images/shrimp-icon.png"),
        title:'Seafood',
        selected:false
    },
    {
        id:3,
        image:require("../../assets/images/soda-icon.png"),
        title:'SoftDrinks',
        selected:false
    },
    {
        id:4,
        image:require("../../assets/images/pizza-icon.png"),
        title:'Pizza',
        selected:false,
    },
    {
        id:5,
        image:require("../../assets/images/shrimp-icon.png"),
        title:'Seafood',
        selected:false
    },
    {
        id:6,
        image:require("../../assets/images/soda-icon.png"),
        title:'SoftDrinks',
        selected:false
    },
]

export default categoriesData